# -*- coding: utf-8 -*-
"""projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h5m0En3mMrUIdN41H6Xbhfl0SgrCvHHv

### DOWNLOADS
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pandas seaborn

"""### IMPORTAÇÕES"""

import pandas as pd
import matplotlib.pyplot as plt

"""### CRIAÇÃO DAS TABELAS"""

# CABECALHO DAS TABELAS

cabecalho_produto = ['id_produto', 'nome_produto', 'valor_unitario', 'categoria_produto']
cabecalho_cliente = ['id_cliente', 'nome', 'data_nascimento', 'email', 'telefone']
cabecalho_venda = ['id_venda', 'id_produto', 'id_cliente', 'quantidade', 'data_venda', 'valor_total']

# tabela produto:
## colunas: id_produto, nome_produto, valor_unitario, categoria_produto

def criar_tabela_produto():
  with open('tabela_produto.csv', 'w') as file:
      tabela_produto = pd.DataFrame(columns=cabecalho_produto)
      tabela_produto.to_csv(file, index=False)

# tabela cliente:
## colunas: id_cliente, nome, data_nascimento, email, telefone

def criar_tabela_cliente():
  with open('tabela_cliente.csv', 'w') as file:
      tabela_cliente = pd.DataFrame(columns=cabecalho_cliente)
      tabela_cliente.to_csv(file, index=False)

# tabela venda:
## colunas: id_venda, id_produto, id_cliente, quantidade, data_venda, valor_total

def criar_tabela_venda():
  with open('tabela_venda.csv', 'w') as file:
      tabela_venda = pd.DataFrame(columns=cabecalho_venda)
      tabela_venda.to_csv(file, index=False)

"""### IMPORTANDO DADOS FICTÍCIOS INICIAIS"""

# INSERÇÃO PRODUTOS

def inserir_produtos():
  dados_produto = [
      [1, 'Notebook Dell Inspiron', 3500.00, 'Informática'],
      [2, 'Mouse Logitech', 120.50, 'Periféricos'],
      [3, 'Teclado Mecânico Redragon', 250.90, 'Periféricos'],
      [4, 'Monitor Samsung 24"', 899.99, 'Informática'],
      [5, 'HD Externo 1TB', 320.00, 'Armazenamento'],
      [6, 'Pen Drive 64GB', 49.90, 'Armazenamento'],
      [7, 'Cadeira Gamer', 1200.00, 'Móveis'],
      [8, 'Webcam Full HD', 210.75, 'Periféricos']
  ]

  novo_df_produto = pd.DataFrame(dados_produto, columns=cabecalho_produto)

  novo_df_produto.to_csv('tabela_produto.csv', mode='a',index=False, header=False)

# INSERÇÃO CLIENTES

def inserir_clientes():
  dados_clientes = [
      [1, 'João Silva', '1990-05-12', 'joao.silva@email.com', '51999990001'],
      [2, 'Maria Oliveira', '1985-11-23', 'maria.oliveira@email.com', '51999990002'],
      [3, 'Carlos Souza', '1992-07-30', 'carlos.souza@email.com', '51999990003'],
      [4, 'Ana Pereira', '1998-02-14', 'ana.pereira@email.com', '51999990004'],
      [5, 'Lucas Fernandes', '1987-09-08', 'lucas.fernandes@email.com', '51999990005'],
      [6, 'Juliana Gomes', '1995-12-19', 'juliana.gomes@email.com', '51999990006'],
      [7, 'Bruno Ribeiro', '1993-03-25', 'bruno.ribeiro@email.com', '51999990007'],
      [8, 'Camila Martins', '2000-06-10', 'camila.martins@email.com', '51999990008']
  ]

  novo_df_clientes = pd.DataFrame(dados_clientes, columns=cabecalho_cliente)

  novo_df_clientes.to_csv('tabela_cliente.csv', mode='a',index=False, header=False)

# INSERÇÃO VENDAS

def inserir_vendas():
  dados_vendas = [
      [1, 1, 1, 2, '2023-08-01', 7000.00],
      [2, 2, 2, 1, '2023-08-02', 120.50],
      [3, 3, 3, 3, '2023-08-03', 752.70],
      [4, 4, 4, 1, '2023-08-04', 899.99],
      [5, 5, 5, 2, '2023-08-05', 640.00],
      [6, 6, 6, 1, '2023-08-06', 49.90],
      [7, 7, 7, 1, '2023-08-07', 1200.00],
      [8, 8, 8, 2, '2023-08-08', 421.50]
  ]

  novo_df_vendas = pd.DataFrame(dados_vendas, columns=cabecalho_venda)

  novo_df_vendas.to_csv('tabela_venda.csv', mode='a',index=False, header=False)

"""### CRUD DOS DADOS"""

# cadastrar cliente

def cadastrar_cliente(nome, data_nascimento, email, telefone):
    try:
        df = pd.read_csv('tabela_cliente.csv')

        id_cliente = df['id_cliente'].max() + 1 if not df.empty else 1

        novo_cliente = pd.DataFrame(
            [[id_cliente, nome, data_nascimento, email, telefone]],
            columns=cabecalho_cliente
        )

        novo_cliente.to_csv('tabela_cliente.csv', mode='a', index=False, header=False)

        return id_cliente

    except Exception as e:
        print("Erro ao cadastrar cliente:", e)

# cadastrar produto

def cadastrar_produto(nome_produto, valor_unitario, categoria_produto):
    try:
        df = pd.read_csv('tabela_produto.csv')

        id_produto = df['id_produto'].max() + 1 if not df.empty else 1

        novo_produto = pd.DataFrame(
            [[id_produto, nome_produto, valor_unitario, categoria_produto]],
            columns=cabecalho_produto
        )

        novo_produto.to_csv('tabela_produto.csv', mode='a', index=False, header=False)

    except Exception as e:
        print("Erro ao cadastrar produto:", e)

# DELETAR PRODUTO

def deletar_produto(id_produto):
    try:
        df = pd.read_csv('tabela_produto.csv')

        df = df[df['id_produto'] != id_produto]

        df.to_csv('tabela_produto.csv', index=False)
    except Exception as e:
        print("Erro ao deletar produto:", e)

# ATUALIZAR PRODUTO

def atualizar_produto(id_produto, novo_nome_produto, novo_valor_unitario, nova_categoria_produto):
    try:
        df = pd.read_csv('tabela_produto.csv')

        df.loc[df['id_produto'] == id_produto, 'nome_produto'] = novo_nome_produto
        df.loc[df['id_produto'] == id_produto, 'valor_unitario'] = novo_valor_unitario
        df.loc[df['id_produto'] == id_produto, 'categoria_produto'] = nova_categoria_produto

        df.to_csv('tabela_produto.csv', index=False)
    except Exception as e:
        print("Erro ao atualizar produto:", e)

# realizar venda

def realizar_venda(id_produto, id_cliente, quantidade, data_venda):
    try:
        df_produto = pd.read_csv('tabela_produto.csv')
        df_cliente = pd.read_csv('tabela_cliente.csv')
        df_venda = pd.read_csv('tabela_venda.csv')

        # validar produto
        if id_produto not in df_produto['id_produto'].values:
            raise ValueError("Produto não encontrado")

        # validar cliente
        if id_cliente not in df_cliente['id_cliente'].values:
            print("Cliente não encontrado. Cadastrando...")
            nome = input("Nome do cliente: ")
            data_nascimento = input("Data de nascimento: ")
            email = input("Email: ")
            telefone = input("Telefone: ")

            id_cliente = cadastrar_cliente(nome, data_nascimento, email, telefone)

        # gerar id venda
        id_venda = df_venda['id_venda'].max() + 1 if not df_venda.empty else 1

        # calcular valor
        valor_unitario = df_produto.loc[
            df_produto['id_produto'] == id_produto, 'valor_unitario'
        ].values[0]

        valor_total = valor_unitario * quantidade

        nova_venda = pd.DataFrame(
            [[id_venda, id_produto, id_cliente, quantidade, data_venda, valor_total]],
            columns=cabecalho_venda
        )

        nova_venda.to_csv('tabela_venda.csv', mode='a', index=False, header=False)

    except Exception as e:
        print("Erro ao realizar venda:", e)

# CADASTRAR CLIENTES

def cadastrar_cliente(nome, data_nascimento, email, telefone):
  try:
    id_cliente = novo_df_clientes['id_cliente'].max() + 1

    novo_cliente = pd.DataFrame([[id_cliente, nome, data_nascimento, email, telefone]], columns=cabecalho_cliente)
  except:
    print("Erro ao cadastrar cliente")

# EXCLUIR CLIENTES

def excluir_cliente(id_cliente):
  try:
    df = pd.read_csv('tabela_cliente.csv')

    df = df[df['id_cliente'] != id_cliente]
    df.to_csv('tabela_cliente.csv', index=False)
  except:
    print("Erro ao excluir cliente")

# ATUALIZAR CLIENTE

def atualizar_cliente(id_cliente, novo_nome, nova_data_nascimento, novo_email, novo_telefone):
  try:
    df = pd.read_csv('tabela_cliente.csv')

    df.loc[df['id_cliente'] == id_cliente, 'nome'] = novo_nome
    df.loc[df['id_cliente'] == id_cliente, 'data_nascimento'] = nova_data_nascimento
    df.loc[df['id_cliente'] == id_cliente, 'email'] = novo_email
    df.loc[df['id_cliente'] == id_cliente, 'telefone'] = novo_telefone
    df.to_csv('tabela_cliente.csv', index=False)
  except:
    print("Erro ao atualizar cliente")

"""### LISTAGENS"""

# LISTAR CLIENTES

def listar_clientes():
  try:
    df = pd.read_csv('tabela_cliente.csv')
    return df
  except:
    print("Erro ao listar clientes")

# LISTAR PRODUTOS

def listar_produtos():
  try:
    df = pd.read_csv('tabela_produto.csv')
    return df
  except:
    print("Erro ao listar produtos")

# LISTAR VENDAS

def listar_vendas():
  try:
    df = pd.read_csv('tabela_venda.csv')
    return df
  except:
    print("Erro ao listar vendas")

"""### RELATORIOS"""

# TOTAL VENDAS

def total_vendas():
  try:
    df = pd.read_csv('tabela_venda.csv')

    total_vendas = df['valor_total'].sum()
    return total_vendas
  except:
    print("Erro ao gerar relatório de total de vendas")

# QUANTIDADE VENDAS

def quantidade_vendas():
  try:
    df = pd.read_csv('tabela_venda.csv')

    quantidade_vendas = df['quantidade'].sum()
    return quantidade_vendas
  except:
    print("Erro ao gerar relatório de quantidade de vendas")

# TOP 3 CATEGORIAS MAIS VENDIDAS

def top3_categorias_mais_vendidas():
  try:
    df_vendas = pd.read_csv('tabela_venda.csv')
    df_produtos = pd.read_csv('tabela_produto.csv')

    df_vendas_produtos = pd.merge(df_vendas, df_produtos, on='id_produto')

    top_categotia_quantidade = df_vendas_produtos.groupby('categoria_produto')['quantidade'].sum().sort_values(ascending=False).head(3)

    return top_categotia_quantidade
  except:
    print("Erro ao gerar relatório de top 3 categorias mais vendidas")

# PRODUTO MAIS VENDIDO

def produto_mais_vendido():
  try:
    df_vendas = pd.read_csv('tabela_venda.csv')
    df_produtos = pd.read_csv('tabela_produto.csv')

    df_vendas_produtos = pd.merge(df_vendas, df_produtos, on='id_produto')

    produto_mais_vendido = df_vendas_produtos.groupby('nome_produto')['quantidade'].sum().idxmax()

    return produto_mais_vendido
  except:
    print("Erro ao gerar relatório de produto mais vendido")

# TICKET MEDIO POR CLIENTE

def ticket_medio_por_cliente():
  try:
    df_vendas = pd.read_csv('tabela_venda.csv')
    df_clientes = pd.read_csv('tabela_cliente.csv')

    df_vendas_clientes = pd.merge(df_vendas, df_clientes, on='id_cliente')

    ticket_medio_por_cliente = df_vendas_clientes.groupby('id_cliente')['valor_total'].mean()

    return ticket_medio_por_cliente
  except:
    print("Erro ao gerar relatório de ticket médio por cliente")

# RELATORIO CONSOLIDADO

def relatorio_consolidado():
  try:
    with open('relatorio_consolidado.txt', 'w') as file:
      file.write("--------------------\n")
      file.write("Relatório Consolidado\n")
      file.write("--------------------\n")
      file.write(f"Total de Vendas: {total_vendas()}\n")
      file.write(f"Quantidade de Vendas: {quantidade_vendas()}\n")
      file.write("Top 3 Categorias Mais Vendidas:\n")
      for categoria, quantidade in top3_categorias_mais_vendidas().items():
        file.write(f"{categoria}: {quantidade}\n")
      file.write(f"Produto Mais Vendido: {produto_mais_vendido()}\n")
      file.write("Ticket Médio por Cliente:\n")
      for id_cliente, ticket_medio in ticket_medio_por_cliente().items():
        file.write(f"Cliente {id_cliente}: {ticket_medio}\n")
  except:
    print("Erro ao gerar relatório consolidado")

"""### ETAPA GRAFICA"""

# DEFININDO DIMENSÕES DO DASH
plt.figure(figsize=(10, 6))
dimensao = [1,3,1]

def proximo_grafico():
  dimensao[2] += 1
  if dimensao[2] > dimensao[1]:
    dimensao[2] = 1
    dimensao[1] += 1

# RELACAO DATA X QUANTIDADE VENDIDA

def grafico_data_quantidade():
  df_vendas = pd.read_csv('tabela_venda.csv')

  df_vendas['data_venda'] = pd.to_datetime(df_vendas['data_venda'], format='%Y-%m-%d')

  plt.subplot(dimensao[0], dimensao[1], dimensao[2])
  plt.title('Vendas por Data')
  plt.xlabel('Data')
  plt.ylabel('Quantidade')

  x = df_vendas['data_venda'].dt.day
  y = df_vendas['quantidade']

  plt.plot(x, y , marker='o')

def grafico_categoria_vendas():
  df_vendas = pd.read_csv('tabela_venda.csv')
  df_produtos = pd.read_csv('tabela_produto.csv')

  df_vendas_produtos = pd.merge(df_vendas, df_produtos, on='id_produto')

  top_categotia_quantidade = df_vendas_produtos.groupby('categoria_produto')['quantidade'].sum()

  plt.subplot(dimensao[0], dimensao[1], dimensao[2])

  plt.title('Categorias x Vendas')
  plt.xlabel('Categoria')
  plt.ylabel('Quantidade')
  plt.xticks(rotation=45)

  x = top_categotia_quantidade.index
  y = top_categotia_quantidade.values

  plt.bar(x, y)

def perfil_clientes():
  df_clientes = pd.read_csv('tabela_cliente.csv')

  df_clientes['data_nascimento'] = pd.to_datetime(df_clientes['data_nascimento'], format='%Y-%m-%d')

  df_clientes['idade'] = (pd.to_datetime('today') - df_clientes['data_nascimento']).dt.days // 365

  df_clientes['perfil'] = pd.cut(
        df_clientes['idade'],
        bins=[0, 29, 59, 120],
        labels=['Jovem', 'Adulto', 'Idoso'],
        right=False
    )

  perfil_cliente = df_clientes.groupby('perfil', observed=False).size()

  plt.subplot(dimensao[0], dimensao[1], dimensao[2])
  plt.title('Perfil dos Clientes')
  plt.xlabel('Perfil')
  plt.ylabel('Quantidade')
  plt.xticks(rotation=45)

  x = perfil_cliente.index
  y = perfil_cliente.values

  plt.bar(x, y)

def mostra_grafico():
  plt.tight_layout()
  plt.show()

"""### PIPELINE"""

# CRIANDO TABELAS

criar_tabela_produto()
criar_tabela_cliente()
criar_tabela_venda()

# INSERINDO DADOS

inserir_produtos()
inserir_clientes()
inserir_vendas()

# RELATORIO

relatorio_consolidado()

# GRAFICOS

grafico_data_quantidade()
proximo_grafico()

grafico_categoria_vendas()
proximo_grafico()

perfil_clientes()

mostra_grafico()

